repos:
  - repo: local
    hooks:
      - id: ruff-check-fix
        name: ruff check (fix)
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python]
        stages: [pre-commit]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python]
        stages: [pre-commit]

      - id: ruff-format-check
        name: ruff format (check)
        entry: uv run ruff format src tests --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check src tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: ty-check
        name: ty check
        entry: uv run ty check src
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

default_language_version:
  python: python3.13
